#Procedural instructions: Twitch Live Streamer Data
## Overview
- The purpose of this document is to be a documentation of the methods used to create a data set using python.
- The data used is derived from the platform Twitch, aspects such as total watch time, average viewership, and amounts of followers for live streaming content creators.
- Analyzing this data can be beneficial to put in perspective the important data to focus on optimizing to anyone apiring to be a content creator.
- Basic software such as python3 and the ability to download the data document will be necessary to conduct this procedure.
### Getting Started: Obtaining the data
- First, setup or use an existing google account to setup a google colab account to access Python3.
- Using [this link](https://www.kaggle.com/datasets/aayushmishra1512/twitchdata?resource=download), download the .csv file of the data.
- Find your google colab notebook folder in your google drive and upload the .csv file.
### Analyzing the data in Python
- To allow Python to access the .csv in google drive, this code bellow is ran

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

- Packages such as pandas and numby needed for Python must be encoded also.
- Use this code next to utilize these packages with np. or pd.

In [ ]:
import numpy as np
import pandas as pd

- Next, to provide consistent acces to the data set in the google doc, run this code below.

In [ ]:
df=pd.read_csv('gdrive/My Drive/Colab Notebooks/twitchdataupdate.csv')

## Investigating the data
- The next step is to filter our data. This is done by running the below code.
- This specific code is used provide the data for rows 1-50 and columns 1-6.

In [ ]:
df.iloc[1:51,1:6]

,Watch time(Minutes),Stream time(minutes),Peak viewers,Average viewers,Followers
1,6091677300,211845,310998,25610,5310163
2,5644590915,515280,387315,10976,1767635
3,3970318140,517740,300575,7714,3944850
4,3671000070,123660,285644,29602,8938903
5,3668799075,82260,263720,42414,1563438
6,3360675195,136275,115633,24181,4074287
7,3301867485,147885,68795,18985,508816
8,2928356940,122490,89387,22381,3530767
9,2865429915,92880,125408,12377,2607076
10,2834436990,108780,142067,25664,5265659
11,2832930285,128490,89170,21739,2666382
12,2674646715,80820,639375,20960,4487489
13,2588632635,58275,240096,42948,5751354
14,2410022550,40575,170115,53986,3983847
15,2408460990,67740,181600,33514,2911316
16,2329440420,115305,107833,19659,2786162
17,2186662470,181230,26999,12201,494445
18,2055003870,103770,89153,19560,3445134
19,2029212570,175230,43615,11343,1264808
20,1943299035,153720,34830,12367,434200
21,1916365860,47325,140557,39848,619382
22,1845157080,100215,125133,17779,2411995
23,1839882465,73065,97540,23794,4450718
24,1811696100,56010,288459,24595,1260160
25,1757406750,54855,538444,28887,3795667
26,1690237110,135675,123796,12868,1792625
27,1659741015,138300,168112,8481,616168
28,1621667925,127815,44976,12869,385250
29,1619144100,87450,234826,6734,1724316
30,1546597380,486510,24470,3187,493207
31,1538511315,141675,81644,10750,2401580
32,1527882945,124680,24892,11220,923448
33,1517612010,172350,90696,8311,4115083
34,1483207890,496950,204491,3020,523758
35,1479214575,134760,122552,9396,6726893
36,1474742220,83010,106900,16422,1075101
37,1470897720,155895,29316,9256,1379123
38,1470431925,45660,305119,28830,973727
39,1464683175,66675,182869,19495,428284
40,1464179820,147660,57431,9728,3135667
41,1461310140,31125,214124,46459,1162746
42,1435735725,118995,45843,11717,381918
43,1412913285,57795,173238,22837,1894953
44,1394312895,141285,35833,9117,1008040
45,1361024835,164235,144066,8066,746865
46,1351758525,37140,171861,36030,934688
47,1347412425,103905,70587,10531,1878416
48,1339344945,193560,44649,6543,470123
49,1339097490,505080,116547,2635,923689
50,1330625430,92160,105359,13189,777510

> Filtering out this data for the Watch time, Stream time, Peak Viewers, Average Viewers, and Amount of followers for the Top 50 Twitch Streamers is done to create more usable and useful subsets.

- We will name this dataframe "Top50Streamers" by running the code below.

In [ ]:
Top50Streamers = df.iloc[1:51,1:6]

> At any time, using this name, the data set can be encoded with the print() function. (example below)

In [ ]:
print(Top50Streamers)

    Watch time(Minutes)  Stream time(minutes)  Peak viewers  Average viewers  \
1            6091677300                211845        310998            25610
2            5644590915                515280        387315            10976
3            3970318140                517740        300575             7714
4            3671000070                123660        285644            29602
5            3668799075                 82260        263720            42414
6            3360675195                136275        115633            24181
7            3301867485                147885         68795            18985
8            2928356940                122490         89387            22381
9            2865429915                 92880        125408            12377
10           2834436990                108780        142067            25664
11           2832930285                128490         89170            21739
12           2674646715                 80820        639375            20960
13           2588632635                 58275        240096            42948
14           2410022550                 40575        170115            53986
15           2408460990                 67740        181600            33514
16           2329440420                115305        107833            19659
17           2186662470                181230         26999            12201
18           2055003870                103770         89153            19560
19           2029212570                175230         43615            11343
20           1943299035                153720         34830            12367
21           1916365860                 47325        140557            39848
22           1845157080                100215        125133            17779
23           1839882465                 73065         97540            23794
24           1811696100                 56010        288459            24595
25           1757406750                 54855        538444            28887
26           1690237110                135675        123796            12868
27           1659741015                138300        168112             8481
28           1621667925                127815         44976            12869
29           1619144100                 87450        234826             6734
30           1546597380                486510         24470             3187
31           1538511315                141675         81644            10750
32           1527882945                124680         24892            11220
33           1517612010                172350         90696             8311
34           1483207890                496950        204491             3020
35           1479214575                134760        122552             9396
36           1474742220                 83010        106900            16422
37           1470897720                155895         29316             9256
38           1470431925                 45660        305119            28830
39           1464683175                 66675        182869            19495
40           1464179820                147660         57431             9728
41           1461310140                 31125        214124            46459
42           1435735725                118995         45843            11717
43           1412913285                 57795        173238            22837
44           1394312895                141285         35833             9117
45           1361024835                164235        144066             8066
46           1351758525                 37140        171861            36030
47           1347412425                103905         70587            10531
48           1339344945                193560         44649             6543
49           1339097490                505080        116547             2635
50           1330625430                 92160        105359            13189

    Followers
1     5310163
2     1767635
3     3944850
4     8938903
5     1563438
6     4074287
7      508816
8     3530767
9     2607076
10    5265659
11    2666382
12    4487489
13    5751354
14    3983847
15    2911316
16    2786162
17     494445
18    3445134
19    1264808
20     434200
21     619382
22    2411995
23    4450718
24    1260160
25    3795667
26    1792625
27     616168
28     385250
29    1724316
30     493207
31    2401580
32     923448
33    4115083
34     523758
35    6726893
36    1075101
37    1379123
38     973727
39     428284
40    3135667
41    1162746
42     381918
43    1894953
44    1008040
45     746865
46     934688
47    1878416
48     470123
49     923689
50     777510

## Finishing Up: Exporting the new subset.
- Now that more efficient subsets of data have been created, it's time to export them as .csv files.
- To export a .csv in our directory, run the below example code of the filename (Top50Streamers) at the beginning and in the parenthesis of the function .to_csv()

In [ ]:
Top50Streamers.to_csv("Top50Streamers.csv", index=False)

> index=False must be included in the parentheses to eliminate the unwanted columns from the original file from being exported.